### ISSUE TITLE
How to specify the subset S of the coordinates?

### ISSUE THREAD

**Issue by szcf-weiya** [remcc/mBART_shlib#1]
Thanks for your great work.

I am wondering how to specify the subject `S` of the coordinates for monotone constraints as stated in your paper.

Based on your chosen priors, 
![image](https://user-images.githubusercontent.com/13688320/142496334-7cb12edd-c7e7-46b0-8941-ebec8f132cb3.png)

the variance in the prior for the constrained coordinates should be scaled on the one of unconstrained, i.e., multiplying `c^2`. However, it seems that the code scales all coordinates.
https://github.com/remcc/mBART_shlib/blob/53ba4cab0227ac92175e7ece75186f1cc66150cf/monbart.R#L82

**Comment by rsparapa** [comment]
That is correct.  The code uses all coordinates.  We have been considering a change but we don't have anything imminent.
